name: Create Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    - name: Set toolchain
      run: rustup override set nightly
    - name: Build
      run: cargo build --verbose --release
    - name: Version
      run: echo "version=$(.\target\release\dr-downloader-cli.exe version no-newline)" >> $GITHUB_OUTPUT
      id: version
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.Version.outputs.version }}
        files: target/release/dr-downloader-cli.exe
