name: Create Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    
    permissions:
      contents: write
    
    steps:
    - name: Test
      id: test
      run: echo "test=hello" >> $GITHUB_OUTPUT
    - name: TestB
      run: echo ${{ steps.Test.outputs.test }}
    - uses: actions/checkout@v3
    - name: Set toolchain
      run: rustup override set nightly
    - name: Build
      run: cargo build --verbose --release
    - name: Set version
      id: set_version
      run: echo "$(.\target\release\dr-downloader-cli.exe version no-newline)" && echo "version=$(.\target\release\dr-downloader-cli.exe version no-newline)" >> $GITHUB_OUTPUT
    - name: Create release
      uses: softprops/action-gh-release@v1 
      with:
        tag_name: ${{ steps.set_version.outputs.version }}
        files: target/release/dr-downloader-cli.exe
