name: Create Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Set toolchain
      run: rustup override set nightly
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3.2.6
      with:
          path: target/
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
    - name: Build
      run: cargo build +nightly --verbose --release
    - name: Version
      run: echo "::set-output name=version::$(.\target\release\dr-downloader-cli.exe version)"
      id: version
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.Version.outputs.version }}
        files: target/release/dr-downloader-cli.exe
